spring:
    #应用唯一标识
    application:
        name: CLOUD-GIS-TM-GATEWAY
    #配置文件
    profiles:
        active: dev
    mvc:
        servlet:
            load-on-startup: 1
    #jdk proxy
    aop:
        proxy-target-class: true
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        joda-date-time-format: yyyy-MM-dd HH:mm:ss
        default-property-inclusion: non_null # 全局jackson配置

#BCOP系统访问云gis系统的token
bcop:
    token: d6d27b1efff34d8d957fbe795c6a5d5e


